fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\Participants
    from_email:
        address: "tbd@something.fr"
        sender_name: "tbd@something.fr"
    registration:
        form:
            type: App\Form\Type\RegistrationForm